name: 'Event Inputs'
description: 'CHANGE ME'
author: 'qoomon'
branding:
  icon: box
  color: blue

inputs:
  redact:
    description: 'Comma separated list of input keys to be redacted'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
