name: Action > Example

on:
  workflow_dispatch:
    inputs:
      val1:
        description: 'Val1'
        default: 'default1'
      val2:
        description: 'Val2'
        default: 'default2'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          retract: /default.*/

